#define FOR_BYTECODES(DO)	\
        DO(INVALID, 1)      \
        DO(DLOAD, 9)		\
        DO(ILOAD, 9)		\
        DO(SLOAD, 3)		\
        DO(DLOAD0, 1)       \
        DO(ILOAD0,  1)      \
        DO(SLOAD0, 1)       \
        DO(DLOAD1, 1)       \
        DO(ILOAD1, 1)       \
        DO(DLOADM1, 1)      \
        DO(ILOADM1, 1)      \
        DO(DADD, 1)         \
        DO(IADD, 1)         \
        DO(DSUB, 1)			\
        DO(ISUB, 1)			\
        DO(DMUL, 1)			\
        DO(IMUL, 1)         \
        DO(DDIV, 1)			\
        DO(IDIV, 1)			\
        DO(IMOD, 1)			\
        DO(DNEG, 1)         \
        DO(INEG, 1)         \
        DO(IPRINT, 1)       \
        DO(DPRINT, 1)       \
        DO(SPRINT, 1)       \
        DO(I2D, 1)          \
        DO(D2I, 1)          \
        DO(S2I, 1)          \
        DO(SWAP, 1)         \
        DO(POP, 1)          \
        DO(LOADDVAR0, 1)	\
        DO(LOADDVAR1, 1)	\
        DO(LOADDVAR2, 1)	\
        DO(LOADDVAR3, 1)	\
        DO(LOADIVAR0, 1)    \
        DO(LOADIVAR1, 1)    \
        DO(LOADIVAR2, 1)    \
        DO(LOADIVAR3, 1)    \
        DO(LOADSVAR0, 1)	\
        DO(LOADSVAR1, 1)	\
        DO(LOADSVAR2, 1)	\
        DO(LOADSVAR3, 1)	\
        DO(STOREDVAR0, 1)   \
        DO(STOREDVAR1, 1)   \
        DO(STOREDVAR2, 1)   \
        DO(STOREDVAR3, 1)   \
        DO(STOREIVAR0, 1)   \
        DO(STOREIVAR1, 1)   \
        DO(STOREIVAR2, 1)   \
        DO(STOREIVAR3, 1)   \
        DO(STORESVAR0, 1)   \
        DO(STORESVAR1, 1)   \
        DO(STORESVAR2, 1)   \
        DO(STORESVAR3, 1)   \
        DO(LOADDVAR, 3)		\
        DO(LOADIVAR, 3)		\
        DO(LOADSVAR, 3)		\
        DO(STOREDVAR, 3)	\
        DO(STOREIVAR, 3)	\
        DO(STORESVAR, 3)	\
        DO(LOADCTXDVAR, 5)	\
        DO(LOADCTXIVAR, 5)	\
        DO(LOADCTXSVAR, 5)	\
        DO(STORECTXDVAR, 5) \
        DO(STORECTXIVAR, 5) \
        DO(STORECTXSVAR, 5) \
        DO(DCMP, 1)			\
        DO(ICMP, 1)			\
        DO(JA, 3)			\
        DO(IFICMPNE, 3)		\
        DO(IFICMPE, 3)		\
        DO(IFICMPG, 3)		\
        DO(IFICMPGE, 3)		\
        DO(IFICMPL, 3)		\
        DO(IFICMPLE, 3)		\
        DO(DUMP, 1)			\
        DO(CALL, 3)			\
        DO(CALLNATIVE, 3)	\
        DO(RETURN, 1)		\
        DO(BREAK, 1)		